LOADING THE DATASET

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/Balanced_dataset.csv')
df.shape

(12500, 2)

In [ ]:
df.columns

Index(['rating', 'review'], dtype='object')

In [ ]:
df['review']=df['review'].astype(str).str.lower()

In [ ]:
df.shape

(12500, 2)

In [ ]:
df.head(5)

   rating                                             review
0       1               very bad product it hangs frequently
1       1  i couldnt wait to get this top in the mail sin...
2       1  i bought a pair of these a month ago and first...
3       1  after reading the previous review i was pretty...
4       1  very bad product battery drains out in minutes...

In [ ]:
df['rating'].value_counts()

rating
1    2500
2    2500
3    2500
4    2500
5    2500
Name: count, dtype: int64

In [ ]:
# Number of reviews to show per rating
n = 5

# Loop through ratings from 1 to 5
for rating in range(1, 6):
    # Filter reviews of the current rating
    filtered_reviews = df[df['rating'] == rating]['review'].dropna()

    # Sample 'n' reviews or all if fewer
    sample_reviews = filtered_reviews.sample(n=min(n, len(filtered_reviews)), random_state=rating)

    # Print the results
    print(f"\nShowing {min(n, len(filtered_reviews))} sample review(s) for Rating {rating}:\n")
    for i, review in enumerate(sample_reviews, 1):
        print(f"{i}. {review.strip()}\n")

Showing 5 sample review(s) for Rating 1:

1. i ran several tests both on my computer and my phone it wrote at mb and read at about to depeneding on its mood i bought this to replace a generic gb class card that i lost so dang small i droped it and could not find it that card actual wrote at to mb and read at mb i went with sandisk because my phone came with a class that performs more like a class what a waste of time refunded this item

2. i was very disappointed with this recipe i agree with tilda it was dry and had no flavor i was expecting an orangey tasting cake and could taste no orange i made this for my grandson age and he did not care for it at all he loves everything i make for him and is so easy to please but this did not please had to throw it away

3. quality of display is bad i got effective speakers and no microsoft installed waste for money they are not replacing also so dont buyy

4. this dress is so cute i went to the store to try it on and although i knew the dress would fit i could not get the zipper up my mom the sales lady and i all tried to get the zipper up and it would not move past the ribbon i wish i could have bought this dress but i cant without a working zipper i tried a size up and every dress at the store that was my size and none of them worked please fix the zipper problem so i can have this dress

5. i was impressed by everything in seasons and everything was just perfect then from bad to worse to unwatchable i am not gonna watch more and i will keep checking the episodes ratings to figure out if they managed to save this if not i dont care about whats next any more it is getting corny and pretentious to the extent that i started to dislike elisabeth moss herself three seasons were enough i have no clue what you are really doing with the storyline nothing looks promising so thank you for the first two seasons but i am not okay with the rest elisabeth moss should find another show to do


Showing 5 sample review(s) for Rating 2:

1. i really wanted to love this dress it is absolutely beautiful the color design and details however whether it is the high neckline or the sleeves it did nothing for me and made me look kinda frumpy though i am slender i have a chest maybe that was the problem

2. super soft fabric however very short in the stride i ordered an xl normally wear i had to return it

3. i purchased the dress with the bowback shift in peach because i loved its nautical theme pattern when i recurve do the dress i found it to be stiff and boxy being a petite shortwaisted person the top portion of the stress hung on my body awkwardly my bra strap was showing in the back and the dress needed to be pulled up about inches to properly sit on my frame i returned the dress

4. i love love love this print and had to have it when retailer had their off sale i think regular price is way too much for this dress as the dress isnt even silk or a better material but once i got this i was so disappointed i ordered my usual size and it was just a balloontent on me i felt like i was wearing a maternity dress plus the ruffle at the top which i thought was a sweet feature felt really awkward and like it was grazing my neck and chin in an annoying way i dont even want t

5. the neck is so big on this sweater i couldnt make it lay right the shape of the sweater is odd it is really wide on the upper torso but tapers near your waist it did not look as depicted on the model the sweater is a lovely color i liked the twotone but overall the fit was too weird for me material is soft and it felt really nice on but just too oddly shaped and a crazy big neck


Showing 5 sample review(s) for Rating 3:

1. im going to do the responsible thing and establish my biases right off the bat i loved the first game so much that for fathers day in my wife managed to buy me a ps and a copy of the last of us part ii and after some family time i sequestered away and played the game start to finish the last of us is my favorite franchise the last of us part ii is my favorite game dina is my favorite character and isabella merced is my favorite currently active actress with all that in mind i should be torn on my reaction to the show a true fan would be appalled at the changes or the casting or the but im not torn i am absolutely in love with this show i find the changes to be a strength rather than a weakness we have already played the game most of us many many times some in the audience never did and have no attachment but do have expectations different from ours the changes in the show accommodate both those they are also narratively interesting most important we need to remember that this is a different perspective a different telling a different approach to a familiar story its no different than how myth changed over time or how different comics give different takes on characters its what makes the mcu work too i could gush on so much about the show but it was more important to remind us all that this show is its own story and that we are being given another way to enjoy something great though i do have a complaint the physicality in abbys character that was actually important and they did everyone a disservice with their choice there for shame

2. the best tv serious for ever now i can see tv after game of thrones please netflix we wait for season

3. slow and expensive better options out there

4. perfect laptop except heating issue

5. i ordered the pink in size xl the color was pretty the problem is the material was too thin and tight it ran at least a size smaller than shown in the photos online


Showing 5 sample review(s) for Rating 4:

1. good laptop performance great display a bit mesh overall great

2. best laptop in segment ok go for it

3. i automatically knocked off one star because every brand that offers size xs and many also offer xxs should also care about us size xls as well i ordered a size large and of course it shows every bump and love handle in back but i recreated a look from my local retailers window they showed a long unbuttoned cotton weave dress over this crochet dress the closest dress pictured online to what i saw is the mabli maxi dress but imagine it opened if it had buttons and in blue with

4. this dress fits great and is very warm for the winter months

5. seems to be working just finebought as a gift for a family member and theyre using it for video recording


Showing 5 sample review(s) for Rating 5:

1. we love this soup it is so fast and economical we make it many times during the winter months

2. i ordered this top in a size m as i heard mara hoffman runs small the size chart on her site would have me order a size s as i have a bust however my bra size is a d or c and the size m is what fit therefore a m might also fit a b and a a as the back is adjustable it even stays up without the halter which is highly unusual for me the only negative that really disappointed me is that the patterns are not quite symmetrical as i expect from this brand and from t

3. i purchased this sandisk ultra gb microsdxc class uhs memory card with adapter for use in my samsung galaxy note i under android apparently my phone had no problem with recognition of this large sd card this makes it possible for me to save a lot of photos and videos i had some feeling its even possible for me to get the gb version to work as well on this phone to make sure that it is fully compatible i did a reformat using the phone of the sd card the phone was able to detect and utilize the full capacity with no problemoverall i am extremely satisfied with this product

4. i love the combination of the three products to buy together the y work well together the fragrance smell nice

5. bought for my new grandson and my daughter loves it helps putting him to sleep

REMOVING STOPWORDS

In [ ]:
%pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk) (4.67.1)

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = word_tokenize(str(text))  # tokenize text
    filtered = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered)


df['review']=df['review'].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
stop_words = set(stopwords.words('english'))

# Display total count and all stopwords
print("Total stopwords:", len(stop_words))
print(sorted(stop_words))  # Sorted alphabetically

Total stopwords: 198
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", "he's", 'her', 'here', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'i', "i'd", "i'll", "i'm", "i've", 'if', 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', "should've", 'shouldn', "shouldn't", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", "we've", 'were', 'weren', "weren't", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", "you're", "you've", 'your', 'yours', 'yourself', 'yourselves']

In [ ]:
# Number of reviews to show per rating
n = 5

# Loop through ratings from 1 to 5
for rating in range(1, 6):
    # Filter reviews of the current rating
    filtered_reviews = df[df['rating'] == rating]['review'].dropna()

    # Sample 'n' reviews or all if fewer
    sample_reviews = filtered_reviews.sample(n=min(n, len(filtered_reviews)), random_state=rating)

    # Print the results
    print(f"\nShowing {min(n, len(filtered_reviews))} sample review(s) for Rating {rating}:\n")
    for i, review in enumerate(sample_reviews, 1):
        print(f"{i}. {review.strip()}\n")

Showing 5 sample review(s) for Rating 1:

1. ran several tests computer phone wrote mb read depeneding mood bought replace generic gb class card lost dang small droped could find card actual wrote mb read mb went sandisk phone came class performs like class waste time refunded item

2. disappointed recipe agree tilda dry flavor expecting orangey tasting cake could taste orange made grandson age care loves everything make easy please please throw away

3. quality display bad got effective speakers microsoft installed waste money replacing also dont buyy

4. dress cute went store try although knew dress would fit could get zipper mom sales lady tried get zipper would move past ribbon wish could bought dress cant without working zipper tried size every dress store size none worked please fix zipper problem dress

5. impressed everything seasons everything perfect bad worse unwatchable gon na watch keep checking episodes ratings figure managed save dont care whats next getting corny pretentious extent started dislike elisabeth moss three seasons enough clue really storyline nothing looks promising thank first two seasons okay rest elisabeth moss find another show


Showing 5 sample review(s) for Rating 2:

1. really wanted love dress absolutely beautiful color design details however whether high neckline sleeves nothing made look kinda frumpy though slender chest maybe problem

2. super soft fabric however short stride ordered xl normally wear return

3. purchased dress bowback shift peach loved nautical theme pattern recurve dress found stiff boxy petite shortwaisted person top portion stress hung body awkwardly bra strap showing back dress needed pulled inches properly sit frame returned dress

4. love love love print retailer sale think regular price way much dress dress isnt even silk better material got disappointed ordered usual size balloontent felt like wearing maternity dress plus ruffle top thought sweet feature felt really awkward like grazing neck chin annoying way dont even want

5. neck big sweater couldnt make lay right shape sweater odd really wide upper torso tapers near waist look depicted model sweater lovely color liked twotone overall fit weird material soft felt really nice oddly shaped crazy big neck


Showing 5 sample review(s) for Rating 3:

1. im going responsible thing establish biases right bat loved first game much fathers day wife managed buy ps copy last us part ii family time sequestered away played game start finish last us favorite franchise last us part ii favorite game dina favorite character isabella merced favorite currently active actress mind torn reaction show true fan would appalled changes casting im torn absolutely love show find changes strength rather weakness already played game us many many times audience never attachment expectations different changes show accommodate also narratively interesting important need remember different perspective different telling different approach familiar story different myth changed time different comics give different takes characters makes mcu work could gush much show important remind us show story given another way enjoy something great though complaint physicality abbys character actually important everyone disservice choice shame

2. best tv serious ever see tv game thrones please netflix wait season

3. slow expensive better options

4. perfect laptop except heating issue

5. ordered pink size xl color pretty problem material thin tight ran least size smaller shown photos online


Showing 5 sample review(s) for Rating 4:

1. good laptop performance great display bit mesh overall great

2. best laptop segment ok go

3. automatically knocked one star every brand offers size xs many also offer xxs also care us size xls well ordered size large course shows every bump love handle back recreated look local retailers window showed long unbuttoned cotton weave dress crochet dress closest dress pictured online saw mabli maxi dress imagine opened buttons blue

4. dress fits great warm winter months

5. seems working finebought gift family member theyre using video recording


Showing 5 sample review(s) for Rating 5:

1. love soup fast economical make many times winter months

2. ordered top size heard mara hoffman runs small size chart site would order size bust however bra size c size fit therefore might also fit b back adjustable even stays without halter highly unusual negative really disappointed patterns quite symmetrical expect brand

3. purchased sandisk ultra gb microsdxc class uhs memory card adapter use samsung galaxy note android apparently phone problem recognition large sd card makes possible save lot photos videos feeling even possible get gb version work well phone make sure fully compatible reformat using phone sd card phone able detect utilize full capacity problemoverall extremely satisfied product

4. love combination three products buy together work well together fragrance smell nice

5. bought new grandson daughter loves helps putting sleep

LEMMATIZATION

In [ ]:
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
lemmatizer = WordNetLemmatizer()
def lemmatize_text(text):
    words = word_tokenize(text)
    lemmatized = [lemmatizer.lemmatize(word) for word in words]
    return ' '.join(lemmatized)
df['review']=df['review'].apply(lemmatize_text)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [ ]:
# Number of reviews to show per rating
n = 5

# Loop through ratings from 1 to 5
for rating in range(1, 6):
    # Filter reviews of the current rating
    filtered_reviews = df[df['rating'] == rating]['review'].dropna()

    # Sample 'n' reviews or all if fewer
    sample_reviews = filtered_reviews.sample(n=min(n, len(filtered_reviews)), random_state=rating)

    # Print the results
    print(f"\nShowing {min(n, len(filtered_reviews))} sample review(s) for Rating {rating}:\n")
    for i, review in enumerate(sample_reviews, 1):
        print(f"{i}. {review.strip()}\n")

Showing 5 sample review(s) for Rating 1:

1. ran several test computer phone wrote mb read depeneding mood bought replace generic gb class card lost dang small droped could find card actual wrote mb read mb went sandisk phone came class performs like class waste time refunded item

2. disappointed recipe agree tilda dry flavor expecting orangey tasting cake could taste orange made grandson age care love everything make easy please please throw away

3. quality display bad got effective speaker microsoft installed waste money replacing also dont buyy

4. dress cute went store try although knew dress would fit could get zipper mom sale lady tried get zipper would move past ribbon wish could bought dress cant without working zipper tried size every dress store size none worked please fix zipper problem dress

5. impressed everything season everything perfect bad worse unwatchable gon na watch keep checking episode rating figure managed save dont care whats next getting corny pretentious extent started dislike elisabeth moss three season enough clue really storyline nothing look promising thank first two season okay rest elisabeth moss find another show


Showing 5 sample review(s) for Rating 2:

1. really wanted love dress absolutely beautiful color design detail however whether high neckline sleeve nothing made look kinda frumpy though slender chest maybe problem

2. super soft fabric however short stride ordered xl normally wear return

3. purchased dress bowback shift peach loved nautical theme pattern recurve dress found stiff boxy petite shortwaisted person top portion stress hung body awkwardly bra strap showing back dress needed pulled inch properly sit frame returned dress

4. love love love print retailer sale think regular price way much dress dress isnt even silk better material got disappointed ordered usual size balloontent felt like wearing maternity dress plus ruffle top thought sweet feature felt really awkward like grazing neck chin annoying way dont even want

5. neck big sweater couldnt make lay right shape sweater odd really wide upper torso taper near waist look depicted model sweater lovely color liked twotone overall fit weird material soft felt really nice oddly shaped crazy big neck


Showing 5 sample review(s) for Rating 3:

1. im going responsible thing establish bias right bat loved first game much father day wife managed buy p copy last u part ii family time sequestered away played game start finish last u favorite franchise last u part ii favorite game dina favorite character isabella merced favorite currently active actress mind torn reaction show true fan would appalled change casting im torn absolutely love show find change strength rather weakness already played game u many many time audience never attachment expectation different change show accommodate also narratively interesting important need remember different perspective different telling different approach familiar story different myth changed time different comic give different take character make mcu work could gush much show important remind u show story given another way enjoy something great though complaint physicality abbys character actually important everyone disservice choice shame

2. best tv serious ever see tv game throne please netflix wait season

3. slow expensive better option

4. perfect laptop except heating issue

5. ordered pink size xl color pretty problem material thin tight ran least size smaller shown photo online


Showing 5 sample review(s) for Rating 4:

1. good laptop performance great display bit mesh overall great

2. best laptop segment ok go

3. automatically knocked one star every brand offer size x many also offer xx also care u size xl well ordered size large course show every bump love handle back recreated look local retailer window showed long unbuttoned cotton weave dress crochet dress closest dress pictured online saw mabli maxi dress imagine opened button blue

4. dress fit great warm winter month

5. seems working finebought gift family member theyre using video recording


Showing 5 sample review(s) for Rating 5:

1. love soup fast economical make many time winter month

2. ordered top size heard mara hoffman run small size chart site would order size bust however bra size c size fit therefore might also fit b back adjustable even stay without halter highly unusual negative really disappointed pattern quite symmetrical expect brand

3. purchased sandisk ultra gb microsdxc class uhs memory card adapter use samsung galaxy note android apparently phone problem recognition large sd card make possible save lot photo video feeling even possible get gb version work well phone make sure fully compatible reformat using phone sd card phone able detect utilize full capacity problemoverall extremely satisfied product

4. love combination three product buy together work well together fragrance smell nice

5. bought new grandson daughter love help putting sleep

In [ ]:
short_counts = df[df['review'].apply(lambda x: len(str(x).split()) < 3)] \
                .groupby('rating').size().reset_index(name='count_less_than_3_words')

print(short_counts)
long_counts = df[df['review'].apply(lambda x: len(str(x).split()) > 50)] \
               .groupby('rating').size().reset_index(name='count_long_reviews')

print(long_counts)

   rating  count_less_than_3_words
0       1                      140
1       2                       70
2       3                       65
3       4                       71
4       5                       96
   rating  count_long_reviews
0       1                 325
1       2                 305
2       3                 412
3       4                 399
4       5                 211

TRAIN_TEST_SPLIT

In [ ]:
from sklearn.model_selection import train_test_split

# Suppose 'df' has columns: 'review' and 'rating'

# Features (X) and labels (y)
X = df['review']
y = df['rating']

# Perform stratified split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

# Optionally combine X and y back into DataFrames
train_df = pd.DataFrame({'review': X_train, 'rating': y_train})
test_df = pd.DataFrame({'review': X_test, 'rating': y_test})

TF-IDF VECTORIZER

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)